apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: was-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /  # 경로 재작성 규칙
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-app-service # was service
            port:
              number: 8090 # was service port 